/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alexander Chauncey and Alex Bennett
	    of http://www.clashnia.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.legit2.Demigods.Database;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;

import com.legit2.Demigods.Utilities.DDataUtil;
import com.legit2.Demigods.Utilities.DObjUtil;
import com.legit2.Demigods.Utilities.DMiscUtil;

/*
 * HASHMAP OF PLAYER'S NAMES
 * CONTAINS EACH PLAYER'S SAVED INFORMATION
 * BE VERY CAREFUL NOT TO SAVE THINGS THAT CAN'T BE WRITTEN
 */
public class DFlatFile
{
	static String path = "plugins/Demigods/";
	
	/*
	 * save : Saves itself, but must be loaded elsewhere (main plugin).
	 */
	public static void save()
	{
		try
		{
			(new File(path + "Data/")).mkdirs();
			(new File(path + "Players/")).mkdirs();
			(new File(path + "Characters/")).mkdirs();
			(new File(path + "DivineBlocks/")).mkdirs();
			for(String data : DDataUtil.getAllPluginData().keySet()) 
			{
				if(data.startsWith("temp_")) continue;
				ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path + "/Data/" + data + ".demi"));
				oos.writeObject(DDataUtil.getAllPluginData().get(data));
				oos.flush();
				oos.close();
			}
			for(String data : DDataUtil.getAllPlayers().keySet()) 
			{
				ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path + "/Players/" + data + ".demi"));
				oos.writeObject(DDataUtil.getAllPlayers().get(data));
				oos.flush();
				oos.close();
			}
			for(Integer data : DDataUtil.getAllChars().keySet()) 
			{
				ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path + "/Characters/" + data + ".demi"));
				oos.writeObject(DDataUtil.getAllChars().get(data));
				oos.flush();
				oos.close();
			}
			
			for(Integer data : DDataUtil.getAllBlockData().keySet()) 
			{
				ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(path + "/DivineBlocks/" + data + ".demi"));
				oos.writeObject(DDataUtil.getAllChars().get(data));
				oos.flush();
				oos.close();
			}
			
			DMiscUtil.info("Success! All hash map data saved to FlatFile!");
		}
		catch(Exception e)
		{
			DMiscUtil.severe("Something went wrong while saving.");
			e.printStackTrace();
		}
	}

	@SuppressWarnings("unchecked")
	public static void load()
	{
		// Data
		File f1 = new File(path + "Data/");
		if(!f1.exists())
		{
			DMiscUtil.info("Creating a new data save.");
			f1.mkdirs();
		}
		File[] list1 = f1.listFiles();
		if(list1 != null)
		{
			for(File element : list1)
			{
				String load = element.getName();
				if(load.endsWith(".demi"))
				{
					load = load.substring(0, load.length() - 5);
					
					try
					{
						ObjectInputStream ois = new ObjectInputStream(new FileInputStream(element));
						Object result = ois.readObject();
						DDataUtil.getAllPluginData().put(load, (HashMap<String, Object>) result);
						ois.close();
					}
					catch(Exception error)
					{
						DMiscUtil.severe("Could not load data " + load);
						error.printStackTrace();
						DMiscUtil.severe("End stack trace for " + load);
					}
				}
			}
		}
		
		// Players
		File f2 = new File(path + "Players/");
		if(!f2.exists())
		{
			DMiscUtil.info("Creating a new player save.");
			f2.mkdirs();
		}
		File[] list2 = f2.listFiles();
		if(list2 != null)
		{
			for(File element : list2)
			{
				String load = element.getName();
				if(load.endsWith(".demi"))
				{
					load = load.substring(0, load.length() - 5);
					
					try
					{
						ObjectInputStream ois = new ObjectInputStream(new FileInputStream(element));
						Object result = ois.readObject();
						DDataUtil.getAllPlayers().put(load, (HashMap<String, Object>) result);
						ois.close();
					}
					catch(Exception error)
					{
						DMiscUtil.severe("Could not load player " + load);
						error.printStackTrace();
						DMiscUtil.severe("End stack trace for " + load);
					}
				}
			}
		}
		
		// Characters
		File f3 = new File(path + "Characters/");
		if(!f3.exists())
		{
			DMiscUtil.info("Creating a new character save.");
			f3.mkdirs();
		}
		File[] list3 = f3.listFiles();
		if(list3 != null)
		{
			for(File element : list3)
			{
				String load = element.getName();
				if(load.endsWith(".demi"))
				{
					load = load.substring(0, load.length() - 5);
					
					Integer intLoad = DObjUtil.toInteger(load);
					
					try
					{
						ObjectInputStream ois = new ObjectInputStream(new FileInputStream(element));
						Object result = ois.readObject();
						DDataUtil.getAllChars().put(intLoad, (HashMap<String, Object>) result);
						ois.close();
					}
					catch(Exception error)
					{
						DMiscUtil.severe("Could not load character " + load);
						error.printStackTrace();
						DMiscUtil.severe("End stack trace for " + load);
					}
				}
			}
		}
		
		// DivineBlocks
		File f4 = new File(path + "DivineBlocks/");
		if(!f4.exists())
		{
			DMiscUtil.info("Creating a new block save.");
			f4.mkdirs();
		}
		File[] list4 = f4.listFiles();
		if(list4 != null)
		{
			for(File element : list4)
			{
				String load = element.getName();
				if(load.endsWith(".demi"))
				{
					load = load.substring(0, load.length() - 5);
					
					Integer intLoad = DObjUtil.toInteger(load);
					
					try
					{
						ObjectInputStream ois = new ObjectInputStream(new FileInputStream(element));
						Object result = ois.readObject();
						DDataUtil.getAllBlockData().put(intLoad, (HashMap<String, Object>) result);
						ois.close();
					}
					catch(Exception error)
					{
						DMiscUtil.severe("Could not load divine block " + load);
						error.printStackTrace();
						DMiscUtil.severe("End stack trace for " + load);
					}
				}
			}
		}
	}
}