/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
	    of http://www.censoredsoftware.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.censoredsoftware.Demigods.Listeners;

import org.bukkit.ChatColor;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.OfflinePlayer;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.player.PlayerInteractEntityEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;

import com.censoredsoftware.Demigods.Demigods;
import com.censoredsoftware.Demigods.Events.Shrine.ShrineCreateEvent;
import com.censoredsoftware.Demigods.Events.Shrine.ShrineRemoveEvent;
import com.censoredsoftware.Demigods.Handlers.Database.DFlatFile;
import com.censoredsoftware.Demigods.Objects.PlayerCharacter;
import com.censoredsoftware.Demigods.Objects.Shrine;

public class DShrineListener implements Listener
{
	public static final Demigods API = Demigods.INSTANCE;
	public static final double FAVOR_MULTIPLIER = API.config.getSettingDouble("global_favor_multiplier");

	/*
	 * --------------------------------------------
	 * Handle Shrine Interactions
	 * --------------------------------------------
	 */
	@EventHandler(priority = EventPriority.HIGH)
	public void shrineBlockInteract(PlayerInteractEvent event)
	{
		// Return if the player is mortal
		if(!API.player.isImmortal(event.getPlayer())) return;
		if(event.getAction() != Action.RIGHT_CLICK_BLOCK) return;

		// Define variables
		Location location = event.getClickedBlock().getLocation();
		Player player = event.getPlayer();
		PlayerCharacter character = API.player.getCurrentChar(player);
		String charAlliance = character.getAlliance();
		String charDeity = character.getDeity();

		if(event.getClickedBlock().getType().equals(Material.GOLD_BLOCK) && event.getAction() == Action.RIGHT_CLICK_BLOCK && event.getPlayer().getItemInHand().getType() == Material.BOOK)
		{
			try
			{
				// Shrine created!
				ShrineCreateEvent shrineCreateEvent = new ShrineCreateEvent(character, location);
				API.getServer().getPluginManager().callEvent(shrineCreateEvent);
				if(shrineCreateEvent.isCancelled()) return;

				new Shrine(character, location);
				location.getWorld().strikeLightningEffect(location);

				if(player.getItemInHand().getAmount() > 1)
				{
					ItemStack books = new ItemStack(player.getItemInHand().getType(), player.getInventory().getItemInHand().getAmount() - 1);
					player.setItemInHand(books);
				}
				else player.getInventory().remove(Material.BOOK);

				player.sendMessage(ChatColor.GRAY + "The " + ChatColor.YELLOW + charAlliance + "s" + ChatColor.GRAY + " are pleased...");
				player.sendMessage(ChatColor.GRAY + "You have created a Shrine in the name of " + ChatColor.YELLOW + charDeity + ChatColor.GRAY + "!");
			}
			catch(Exception e)
			{
				// Creation of shrine failed...
				e.printStackTrace();
			}
		}

		useShrine(player, location);
	}

	@EventHandler(priority = EventPriority.HIGH)
	public void shrineEntityInteract(PlayerInteractEntityEvent event)
	{
		// Define variables
		Location location = event.getRightClicked().getLocation().subtract(0.5, 1.0, 0.5);
		Player player = event.getPlayer();

		useShrine(player, location);
	}

	private void useShrine(Player player, Location location)
	{
		// First handle admin wand
		if(API.admin.useWand(player) && API.block.isShrine(location))
		{
			if(API.data.hasTimedData(player, "temp_destroy_shrine"))
			{
				Shrine shrine = API.block.getShrine(location);

				ShrineRemoveEvent shrineRemoveEvent = new ShrineRemoveEvent(shrine.getOwner(), location);
				API.getServer().getPluginManager().callEvent(shrineRemoveEvent);
				if(shrineRemoveEvent.isCancelled()) return;

				// We can destroy the Shrine
				API.block.getShrine(location).remove();
				API.data.removePlayerData(player, "temp_destroy_shrine");

				// Drop the block of gold and book
				location.getWorld().dropItemNaturally(location, new ItemStack(Material.GOLD_BLOCK, 1));
				location.getWorld().dropItemNaturally(location, new ItemStack(Material.BOOK, 1));

				// Save Divine Blocks
				DFlatFile.saveBlocks();

				player.sendMessage(ChatColor.GREEN + "Shrine removed!");
				return;
			}
			else
			{
				API.data.saveTimedData(player, "temp_destroy_shrine", true, 5);
				player.sendMessage(ChatColor.RED + "Right-click this Shrine again to remove it.");
				return;
			}
		}

		// Define variables
		PlayerCharacter character = API.player.getCurrentChar(player);

		// Return if the player is mortal
		if(character == null || !character.isImmortal())
		{
			player.sendMessage(ChatColor.RED + "You must be immortal to use that!");
			return;
		}

		try
		{
			// Check if block is divine
			Shrine shrine = API.block.getShrine(location);
			if(shrine == null) return;

			int shrineOwner = shrine.getOwner().getID();
			String shrineDeity = shrine.getDeity();

			if(API.block.isShrine(location))
			{
				// Check if character has deity
				if(character.hasDeity(shrineDeity))
				{
					// Open the tribute inventory
					Inventory ii = API.getServer().createInventory(player, 27, "Shrine of " + shrineDeity);
					player.openInventory(ii);
					API.data.saveCharData(character.getID(), "temp_tributing", shrineOwner);
					return;
				}
				player.sendMessage(ChatColor.YELLOW + "You must be allied to " + shrineDeity + " in order to tribute here.");
			}
		}
		catch(Exception e)
		{
			// Print error for debugging
			e.printStackTrace();
		}
	}

	/*
	 * --------------------------------------------
	 * Handle Player Tributing
	 * --------------------------------------------
	 */
	@EventHandler(priority = EventPriority.MONITOR)
	public void playerTribute(InventoryCloseEvent event)
	{
		try
		{
			if(!(event.getPlayer() instanceof Player)) return;
			Player player = (Player) event.getPlayer();
			PlayerCharacter character = API.player.getCurrentChar(player);
			if(character == null || !character.isImmortal()) return;

			String charDeity = character.getDeity();
			int charID = character.getID();

			// If it isn't a tribute chest then break the method
			if(!event.getInventory().getName().contains("Shrine")) return;

			// Get the creator of the shrine
			int shrineOwnerID = API.object.toInteger(API.data.getCharData(character.getID(), "temp_tributing"));
			API.data.removeCharData(charID, "temp_tributing");

			// Calculate value of chest
			int tributeValue = 0, items = 0;
			for(ItemStack ii : event.getInventory().getContents())
			{
				if(ii != null)
				{
					tributeValue += API.value.getTributeValue(ii);
					items++;
				}
			}

			tributeValue *= FAVOR_MULTIPLIER;

			// Process tributes and send messages
			int favorBefore = character.getMaxFavor();
			int devotionBefore = character.getDevotion();

			// Update the character's favor and devotion
			character.addMaxFavor(tributeValue / 5);
			character.giveDevotion(tributeValue);

			if(character.getDevotion() > devotionBefore) player.sendMessage(ChatColor.GRAY + "Your devotion to " + ChatColor.YELLOW + charDeity + ChatColor.GRAY + " has increased to " + ChatColor.GREEN + character.getDevotion() + ChatColor.GRAY + ".");
			if(character.getMaxFavor() > favorBefore) player.sendMessage(ChatColor.GRAY + "Your favor cap has increased to " + ChatColor.GREEN + character.getMaxFavor() + ChatColor.GRAY + ".");

			if(favorBefore != character.getMaxFavor() && devotionBefore != character.getDevotion() && items > 0)
			{
				// Update the shrine owner's devotion and let them know
				OfflinePlayer shrineOwnerPlayer = API.character.getOwner(shrineOwnerID);
				if(!API.character.getOwner(charID).equals(shrineOwnerPlayer))
				{
					// TODO: FIX THIS
					// DCharUtil.giveDevotion(shrineOwner, tributeValue / 7);
					if(shrineOwnerPlayer.isOnline())
					{
						((Player) shrineOwnerPlayer).sendMessage(ChatColor.YELLOW + "Someone just tributed at your shrine!");
						((Player) shrineOwnerPlayer).sendMessage(ChatColor.GRAY + "Your devotion has increased to " + API.character.getChar(shrineOwnerID).getDevotion() + "!");
					}
				}
			}
			else
			{
				// If they aren't good enough let them know
				if(items > 0) player.sendMessage(ChatColor.RED + "Your tributes were insufficient for " + charDeity + "'s blessings.");
			}

			// Clear the tribute case
			event.getInventory().clear();
		}
		catch(Exception e)
		{
			// Print error for debugging
			e.printStackTrace();
		}
	}
}
