/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alexander Chauncey and Alex Bennett
	    of http://www.clashnia.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.legit2.Demigods.Utilities;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Map.Entry;

import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;

import com.legit2.Demigods.Utilities.DMiscUtil;

public class DDeityUtil 
{
	/*
	 *  getDeityClass() : Returns the string of the (String)deity's classpath.
	 */
	public static String getDeityClass(String deity)
	{
		return DDataUtil.getPluginData("temp_deity_classes", deity).toString();
	}
	
	/*
	 *  invokeDeityMethod() : Invokes a static method (with no paramaters) from inside a deity class.
	 */
	@SuppressWarnings("rawtypes")
	public static Object invokeDeityMethod(String deityClass, String method) throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
	{		
		// No Paramaters
		Class noparams[] = {};
		
		// Creates a new instance of the deity class
		Object obj = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).newInstance();
		
		// Load everything else for the Deity (Listener, etc.)
		Method toInvoke = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).getMethod(method, noparams);
		
		return toInvoke.invoke(obj, (Object[])null);
	}
	
	/*
	 *  invokeDeityMethodWithString() : Invokes a static method, with a String, from inside a deity class.
	 */
	public static Object invokeDeityMethodWithString(String deityClass, String method, String paramater) throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
	{			
		// Creates a new instance of the deity class
		Object obj = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).newInstance();
		
		// Load everything else for the Deity (Listener, etc.)
		Method toInvoke = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).getMethod(method, String.class);
		
		return toInvoke.invoke(obj, paramater);
	}
	
	/*
	 *  invokeDeityMethodWithStringArray() : Invokes a static method, with an ArrayList, from inside a deity class.
	 */
	public static Object invokeDeityMethodWithStringArray(String deityClass, String method, Player player, String[] paramater) throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
	{			
		// Creates a new instance of the deity class
		Object obj = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).newInstance();
		
		// Load everything else for the Deity (Listener, etc.)
		Method toInvoke = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).getMethod(method, Player.class, String[].class);
		
		return toInvoke.invoke(obj, player, paramater);
	}
	
	/*
	 *  invokeDeityMethodWithPlayer() : Invokes a static method, with a Player, from inside a deity class.
	 */
	public static Object invokeDeityMethodWithPlayer(String deityClass, String method, Player paramater) throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
	{			
		// Creates a new instance of the deity class
		Object obj = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).newInstance();
		
		// Load everything else for the Deity (Listener, etc.)
		Method toInvoke = Class.forName(deityClass, true, DMiscUtil.getPlugin().getClass().getClassLoader()).getMethod(method, Player.class);
		
		return toInvoke.invoke(obj, paramater);
	}
	
	/*
	 *  invokeDeityCommand : Invokes a deity command.
	 */
	@SuppressWarnings("unchecked")
	public static boolean invokeDeityCommand(Player player, String[] args) throws NoSuchMethodException, SecurityException, ClassNotFoundException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException
	{
		String deity = null;
		String command = args[0];
		
		for(Entry<String, Object> entry : DDataUtil.getAllPluginData().get("temp_deity_commands").entrySet())
		{	
			if(((ArrayList<String>) entry.getValue()).contains(command.toLowerCase()))
			{
				deity = entry.getKey();
				break;
			}
		}
		if(deity == null) return false;
		
		String deityClass = getDeityClass(deity);

		invokeDeityMethodWithStringArray(deityClass, command + "Command", player, args);
		return true;
	}
	
	/*
	 *  getLoadedDeityNames() : Returns a ArrayList<String> of all the loaded deities' names.
	 */
	public static ArrayList<String> getLoadedDeityNames()
	{
		ArrayList<String> toReturn = new ArrayList<String>();
		
		for(String deity : DDataUtil.getAllPluginData().get("temp_deity_alliances").keySet())
		{
			toReturn.add(deity);
		}
		
		return toReturn;
	}
	
	/*
	 *  getLoadedDeityAlliances() : Returns a ArrayList<String> of all the loaded deities' alliances.
	 */
	public static ArrayList<String> getLoadedDeityAlliances()
	{
		ArrayList<String> toReturn = new ArrayList<String>();
		
		for(Object alliance : DDataUtil.getAllPluginData().get("temp_deity_alliances").values().toArray())
		{
			if(toReturn.contains((String) alliance)) continue;
			toReturn.add((String) alliance);
		}
		
		return toReturn;
	}
	
	/*
	 *  getDeityAlliance() : Returns a String of a loaded (String)deity's alliance.
	 */
	public static String getDeityAlliance(String deity)
	{
		String toReturn = (String) DDataUtil.getPluginData("temp_deity_alliances", deity.toLowerCase());
		return toReturn;
	}
	
	/*
	 *  getDeityColor() : Returns a ChatColor of a loaded (String)deity.
	 */
	public static ChatColor getDeityColor(String deity)
	{
		ChatColor toReturn = (ChatColor) DDataUtil.getPluginData("temp_deity_colors", deity.toLowerCase());
		return toReturn;
	}
	
	/*
	 *  getDeityClaimItems() : Returns an ArrayList<Material> of a loaded (String)deity's claim items.
	 */
	@SuppressWarnings("unchecked")
	public static ArrayList<Material> getDeityClaimItems(String deity)
	{
		ArrayList<Material> toReturn = (ArrayList<Material>) DDataUtil.getPluginData("temp_deity_claim_items", deity.toLowerCase());
		return toReturn;
	}
	
	/*
	 *  getAllDeitiesInAlliance() : Returns a ArrayList<String> of all the loaded deities' names.
	 */
	public static ArrayList<String> getAllDeitiesInAlliance(String alliance)
	{
		ArrayList<String> toReturn = new ArrayList<String>();
		
		for(String deity : DDataUtil.getAllPluginData().get("temp_deity_alliances").keySet())
		{
			if(!(getDeityAlliance(deity)).equalsIgnoreCase(alliance.toLowerCase())) continue;
			toReturn.add(deity);
		}
		
		return toReturn;
	}
	
	/*
	 *  getAllDeityCommands() : Returns a ArrayList<String> of all the loaded deities' commands.
	 */
	public static ArrayList<String> getAllDeityCommands()
	{
		ArrayList<String> toReturn = new ArrayList<String>();
		
		for(Entry<String, Object> deityCommands : DDataUtil.getAllPluginData().get("temp_deity_commands").entrySet())
		{	
			toReturn.add(deityCommands.getValue().toString());
		}
		
		return toReturn;
	}
	

}
