/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alexander Chauncey and Alex Bennett
	    of http://www.clashnia.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.legit2.Demigods.Utilities;

import org.bukkit.Location;
import org.bukkit.entity.Player;

import com.legit2.Demigods.DDivineBlocks;
import com.legit2.Demigods.Libraries.DivineBlock;
import com.massivecraft.factions.Board;
import com.massivecraft.factions.FLocation;
import com.massivecraft.factions.Faction;
import com.sk89q.worldguard.protection.ApplicableRegionSet;
import com.sk89q.worldguard.protection.flags.DefaultFlag;
import com.sk89q.worldguard.protection.regions.ProtectedRegion;

public class DZoneUtil
{
	public static int SHRINE_RADIUS = 8;
	public static int ALTAR_RADIUS = 16;
	
	/* --------------------------------------------
	 *  No PVP Zones
	 * --------------------------------------------
	 * 
	 *  zoneNoPVP() : Returns true if (Location)location is within a no PVP zone.
	 */
	public static boolean zoneNoPVP(Location location)
	{
		if(DConfigUtil.getSettingBoolean("allow_skills_anywhere")) return false;
		if(DConfigUtil.getSettingBoolean("use_dynamic_pvp_zones"))
		{
			// Currently only supports WorldGuard for dynamic PVP zones
			if(DMiscUtil.getPlugin().WORLDGUARD != null) return !canWorldGuardDynamicPVPAndNotAltar(location);
			else return zoneAltar(location) != null;
		}
		else
		{
			if(DMiscUtil.getPlugin().WORLDGUARD != null && DMiscUtil.getPlugin().FACTIONS != null) return !canWorldGuardAndFactionsPVP(location);
			else if(DMiscUtil.getPlugin().WORLDGUARD != null) return !canWorldGuardFlagPVP(location);
			else if(DMiscUtil.getPlugin().FACTIONS != null) return !canFactionsPVP(location);
			else return false;
		}
	}
	
	/* 
	 *  enterZoneNoPVP() : Returns true if entering a no PVP zone.
	 */
	public static boolean enterZoneNoPVP(Location to, Location from)
	{
		if(!DZoneUtil.zoneNoPVP(from) && DZoneUtil.zoneNoPVP(to)) return true;
		else return false;
	}
	
	/* 
	 *  exitZoneNoPVP() : Returns true if exiting a no PVP zone.
	 */
	public static boolean exitZoneNoPVP(Location to, Location from)
	{
		return enterZoneNoPVP(from, to);
	}
	
    /*
	 *  canWorldGuardAndFactionsPVP() : Returns true if PVP is allowed at (Location)location.
	 */
    public static boolean canWorldGuardAndFactionsPVP(Location location)
    {
    	if(canFactionsPVP(location) && canWorldGuardFlagPVP(location)) return true;
    	else if(!canFactionsPVP(location)) return false;
    	else if(!canWorldGuardFlagPVP(location)) return false;
    	else return true;
    }
	
    /*
	 *  canWorldGuardDynamicPVPAndNotAltar() : Returns true if PVP is allowed at (Location)location, and it's not an Altar.
	 */
    public static boolean canWorldGuardDynamicPVPAndNotAltar(Location location)
    {
    	if(!(zoneAltar(location) != null) && canWorldGuardDynamicPVP(location)) return true;
    	else if(!canWorldGuardDynamicPVP(location)) return false;
    	else if(zoneAltar(location) != null) return false;
    	else return true;
    }
    
    /*
	 *  canWorldGuardDynamicPVP() : Returns true if PVP is allowed at (Location)location.
	 */
    public static boolean canWorldGuardDynamicPVP(Location location)
    {	    
	    ApplicableRegionSet set = DMiscUtil.getPlugin().WORLDGUARD.getRegionManager(location.getWorld()).getApplicableRegions(location);
	    for (ProtectedRegion region : set)
		{
	    	if(region.getId().toLowerCase().contains("nopvp")) return false;
		}
	    return true;
    }
    
    /*
	 *  canWorldGuardFlagPVP() : Returns true if PVP is allowed at (Location)location.
	 */
    public static boolean canWorldGuardFlagPVP(Location location)
    {	    
    	ApplicableRegionSet set = DMiscUtil.getPlugin().WORLDGUARD.getRegionManager(location.getWorld()).getApplicableRegions(location);
		return !set.allows(DefaultFlag.PVP);
    }
            
    /*
	 *  canFactionsPVP() : Returns true if PVP is allowed at (Location)location.
	 */
    public static boolean canFactionsPVP(Location location)
    {
		Faction faction = Board.getFactionAt(new FLocation(location.getBlock()));
		return !(faction.isPeaceful() || faction.isSafeZone());
	}
    

    
    /* --------------------------------------------
	 *  No Build Zones
	 * --------------------------------------------
	 * 
	 *  zoneNoBuild() : Returns true if (Location)location is within a no Build zone for (Player)player.
	 */
	public static boolean zoneNoBuild(Player player, Location location)
	{
		if(DMiscUtil.getPlugin().WORLDGUARD != null && DMiscUtil.getPlugin().FACTIONS != null) return !canWorldGuardAndFactionsBuild(player, location);
		else if(DMiscUtil.getPlugin().WORLDGUARD != null) return !canWorldGuardBuild(player, location);
		else if(DMiscUtil.getPlugin().FACTIONS != null) return !canFactionsBuild(player, location);
		else return false;
	}
	
	/* 
	 *  enterZoneNoBuild() : Returns true if entering a no Build zone.
	 */
	public static boolean enterZoneNoBuild(Player player, Location to, Location from)
	{
		if(!DZoneUtil.zoneNoBuild(player, from) && DZoneUtil.zoneNoBuild(player, to)) return true;
		else return false;
	}
	
	/* 
	 *  exitZoneNoBuilt() : Returns true if exiting a no Build zone.
	 */
	public static boolean exitZoneNoBuild(Player player, Location to, Location from)
	{
		return enterZoneNoBuild(player, from, to);
	}
	
    /*
	 *  canWorldGuardAndFactionsBuild() : Returns true if (Player)player is allowed to build at (Location)location.
	 */
    public static boolean canWorldGuardAndFactionsBuild(Player player, Location location)
    {
    	if(canFactionsBuild(player, location) && canWorldGuardBuild(player, location)) return true;
    	else if(!canFactionsBuild(player, location)) return false;
    	else if(!canWorldGuardBuild(player, location)) return false;
    	else return true;
    }
	
    /*
	 *  canWorldGuardBuild() : Returns true if (Player)player can build at (Location)location.
	 */
    public static boolean canWorldGuardBuild(Player player, Location location)
    {
        return DMiscUtil.getPlugin().WORLDGUARD.canBuild(player, location);
    }
    
    /*
	 *  canFactionsBuild() : Returns true if (Player)player can build at (Location)location.
	 */
    public static boolean canFactionsBuild(Player player, Location location)
    {
        return DMiscUtil.getPlugin().FACTIONS.isPlayerAllowedToBuildHere(player, location);
    }
    
    /* --------------------------------------------
	 *  DivineBlock Zones
	 * --------------------------------------------
	 * 
	 *  zoneShrine() : Returns a DivineBlock if (Location)location is within a Shrine's zone.
	 */
    public static DivineBlock zoneShrine(Location location)
    {
    	for(DivineBlock divineBlock : DDivineBlocks.getAllShrineBlocks())
		{	
    		if(location.getWorld() != divineBlock.getLocation().getWorld()) continue;
    		if(location.distance(divineBlock.getLocation()) <= SHRINE_RADIUS) return divineBlock;
		}
    	return null;
    }
    
	/* 
	 *  zoneShrineOwner() : Returns the owner of a Shrine from (Location)location.
	 */
	public static int zoneShrineOwner(Location location)
	{
		for(Location divineBlock : DDivineBlocks.getAllShrines())
		{	
			if(location.getWorld() != divineBlock.getWorld()) continue;
    		if(location.distance(divineBlock) <= SHRINE_RADIUS) return DDivineBlocks.getShrineOwner(divineBlock);
		}
		return -1;
	}
    
	/* 
	 *  enterZoneShrine() : Returns true if entering a Shrine zone.
	 */
	public static boolean enterZoneShrine(Location to, Location from)
	{
		if(!(DZoneUtil.zoneShrine(from) != null) && DZoneUtil.zoneShrine(to) != null) return true;
		else return false;
	}
	
	/* 
	 *  exitZoneShrine() : Returns true if exiting a Shrine zone.
	 */
	public static boolean exitZoneShrine(Location to, Location from)
	{
		return enterZoneShrine(from, to);
	}
    
	/* 
	 *  zoneAltar() : Returns true if (Location)location is within an Altar's zone.
	 */
    public static DivineBlock zoneAltar(Location location)
    {
    	for(DivineBlock divineBlock : DDivineBlocks.getAllAltarBlocks())
		{	
    		DivineBlock parentBlock = DDivineBlocks.getDivineBlock((divineBlock.getParent()));
    		if(location.getWorld() != parentBlock.getLocation().getWorld()) continue;
    		if(location.distance(parentBlock.getLocation()) <= ALTAR_RADIUS) return parentBlock;
		}
    	return null;
    }
    
	/* 
	 *  enterZoneAltar() : Returns true if entering an Altar zone.
	 */
	public static boolean enterZoneAltar(Location to, Location from)
	{
		if(!(DZoneUtil.zoneAltar(from) != null) && DZoneUtil.zoneAltar(to) != null) return true;
		else return false;
	}
	
	/* 
	 *  exitZoneAltar() : Returns true if exiting an Altar zone.
	 */
	public static boolean exitZoneAltar(Location to, Location from)
	{
		return enterZoneAltar(from, to);
	}
}