/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
	    of http://www.censoredsoftware.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.censoredsoftware.Demigods.Objects;

import java.io.Serializable;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;

import com.censoredsoftware.Demigods.Demigods;

public class Shrine implements Serializable
{
	private static final Demigods API = Demigods.INSTANCE;
	private static final long serialVersionUID = 1020598192563856384L;

	private int id, owner;
	private String deity;
	private ProtectedBlock block;
	private SerialLocation location;

	public Shrine(int id, PlayerCharacter character, Location location)
	{
		this.id = id;
		this.location = new SerialLocation(location);
		this.owner = character.getID();
		this.deity = character.getDeity();

		// Generate the Shrine
		generate();

		save();
	}

	/*
	 * save() : Saves the Shrine to a HashMap.
	 */
	private void save()
	{
		API.data.saveBlockData("shrines", this.id, this);
	}

	/*
	 * remove() : Removes the Shrine.
	 */
	public synchronized void remove()
	{
		API.data.removeBlockData("shrines", this.id);

		Location location = this.location.unserialize();
		location.getBlock().setType(Material.AIR);

		Location locToMatch = location.add(0.5, 1.0, 0.5);
		for(Entity entity : location.getWorld().getEntities())
		{
			if(entity.getLocation().equals(locToMatch))
			{
				entity.remove();
			}
		}
	}

	/*
	 * getID() : Returns the ID for the Shrine.
	 */
	public int getID()
	{
		return this.id;
	}

	/*
	 * getOwner() : Returns the owner ID for the Shrine.
	 */
	public PlayerCharacter getOwner()
	{
		return API.character.getChar(this.owner);
	}

	/*
	 * getDeity() : Returns the deity for the Shrine.
	 */
	public String getDeity()
	{
		return this.deity;
	}

	/*
	 * getLocation() : Returns the location of this Shrine.
	 */
	public Location getLocation()
	{
		return this.location.unserialize();
	}

	/**
	 * Generates the physical Shrine structure.
	 */
	public synchronized void generate()
	{
		Location location = this.getLocation();

		// Remove entity to be safe
		Location locToMatch = this.getLocation().add(0.5, 1.0, 0.5);
		for(Entity entity : location.getWorld().getEntities())
		{
			if(entity.getLocation().equals(locToMatch))
			{
				entity.remove();
			}
		}

		// Set bedrock
		this.block = new ProtectedBlock(location, "shrine", Material.BEDROCK);

		// Spawn the Entity
		location.getWorld().spawnEntity(location.add(0.5, 0.0, 0.5), EntityType.ENDER_CRYSTAL);
	}

	@Override
	public boolean equals(Object object)
	{
		return !(object == null || !(object instanceof Shrine)) && this.id == parse(object).getID();
	}

	@Override
	public String toString()
	{
		return "Shrine{id=" + this.id + ",owner=" + this.owner + ",location=" + location.unserialize().getWorld().getName() + "," + location.unserialize().getX() + "," + location.unserialize().getY() + "," + location.unserialize().getZ() + "}";
	}

	/**
	 * Parses the save object into a new Shrine object and returns it.
	 * 
	 * @param object the save to parse.
	 * @return Shrine
	 */
	public static Shrine parse(Object object)
	{
		if(object instanceof Shrine) return (Shrine) object;
		else if(object instanceof String)
		{
			// Cast the object into a string
			String string = (String) object;

			// Validate that it's a Shrine save
			if(!string.startsWith("Shrine{id=")) return null;

			// Begin splitting the string into the different variables to parse with
			string = string.substring(9).replace("}", "");
			String[] data = string.split(",");

			// Parse the location
			String[] locs = data[2].substring(9).split(",");
			Location location = new Location(Bukkit.getWorld(locs[0]), API.object.toInteger(locs[1]), API.object.toInteger(locs[2]), API.object.toInteger(locs[3]));

			// Build the object
			Shrine shrine = new Shrine(API.object.toInteger(data[0]), API.character.getChar(API.object.toInteger(data[1])), location);

			// Return the new Shrine
			return shrine;
		}

		return null;
	}
}
