/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
	    of http://www.censoredsoftware.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.censoredsoftware.Demigods.API;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;

import org.bukkit.Location;
import org.bukkit.entity.Player;

import com.censoredsoftware.Demigods.Demigods;
import com.censoredsoftware.Demigods.Events.Battle.BattleCombineEvent;
import com.censoredsoftware.Demigods.Events.Battle.BattleEndEvent;
import com.censoredsoftware.Demigods.Events.Battle.BattleParticipateEvent;
import com.censoredsoftware.Demigods.Events.Battle.BattleStartEvent;
import com.censoredsoftware.Demigods.Objects.Battle;
import com.censoredsoftware.Demigods.Objects.PlayerCharacter;
import com.censoredsoftware.Demigods.Objects.SerialLocation;

@SuppressWarnings("ALL")
/**
 * Handles all battle-related methods.
 */
public class BattleAPI
{
	private static final Demigods API = Demigods.INSTANCE;
	private static final int BATTLEDISTANCE = 16; // TODO

	/**
	 * Returns the Battle object with the id <code>battleID</code>.
	 * 
	 * @param battleID the id to look for.
	 * @return Battle
	 */
	public Battle getBattle(int battleID)
	{
		HashMap<Integer, HashMap<String, Object>> battles = API.data.getAllBattles();

		if(battles.containsKey(battleID)) return (Battle) battles.get(battleID).get("battle_object");
		else return null;
	}

	/**
	 * Returns an ArrayList of all Battles.
	 * 
	 * @return ArrayList
	 */
	public ArrayList<Battle> getAll()
	{
		ArrayList<Battle> battles = new ArrayList<Battle>();
		for(Entry<Integer, HashMap<String, Object>> allBattles : API.data.getAllBattles().entrySet())
		{
			Battle battle = (Battle) allBattles.getValue().get("battle_object");
			battles.add(battle);
		}
		return battles;
	}

	/**
	 * Returns an ArrayList of all active Battles.
	 * 
	 * @return ArrayList
	 */
	public ArrayList<Battle> getAllActive()
	{
		ArrayList<Battle> battles = new ArrayList<Battle>();
		for(Entry<Integer, HashMap<String, Object>> allBattles : API.data.getAllBattles().entrySet())
		{
			Battle battle = (Battle) allBattles.getValue().get("battle_object");
			if(battle.isActive()) battles.add(battle);
		}
		return battles;
	}

	/**
	 * Returns an ArrayList of all active battles near <code>location</code>.
	 * 
	 * @param location the location to check.
	 * @return Battle
	 */
	public Battle getActiveBattle(Location location)
	{
		for(Battle battle : getAllActive())
		{
			if(isNearBattle(battle, location)) return battle;
		}
		return null;
	}

	/**
	 * Returns the current active Battle for <code>character</code>.
	 * 
	 * @param character the character whose active battle to return.
	 * @return Battle
	 */
	public Battle getActiveBattle(PlayerCharacter character)
	{
		for(Battle battle : getAllActive())
		{
			if(isInBattle(battle, character)) return battle;
		}
		return null;
	}

	/**
	 * Returns true if <code>location</code> is near <code>battle</code>.
	 * 
	 * @param battle the battle to compare.
	 * @param location the location to compare.
	 * @return boolean
	 */
	public boolean isNearBattle(Battle battle, Location location)
	{
		for(SerialLocation battleLocation : battle.getLocations())
		{
			if(location.distance(battleLocation.unserialize()) <= BATTLEDISTANCE) return true;
		}
		return false;
	}

	/**
	 * Returns true if <code>character</code> is involved in the given <code>battle</code>.
	 * 
	 * @param battle the battle to check for.
	 * @param character the character to check.
	 * @return boolean
	 */
	public boolean isInBattle(Battle battle, PlayerCharacter character)
	{
		for(int charID : battle.getCharIDs())
		{
			if(character.getID() == charID) return true;
		}
		return false;
	}

	/**
	 * Returns true if the <code>location</code> is near any active battle.
	 * 
	 * @param location the location to check.
	 * @return boolean
	 */
	public boolean isNearAnyActiveBattle(Location location)
	{
		for(Battle battle : getAllActive())
		{
			if(isNearBattle(battle, location)) return true;
		}
		return false;
	}

	/**
	 * Returns true if the <code>character</code> is involved in an active battle.
	 * 
	 * @param character the character to check.
	 * @return boolean
	 */
	public boolean isInAnyActiveBattle(PlayerCharacter character)
	{
		for(Battle battle : getAllActive())
		{
			if(isInBattle(battle, character)) return true;
		}
		return false;
	}

	/**
	 * Returns true if the <code>command</code> is blocked during battles.
	 * 
	 * @param command the command to check.
	 * @return boolean
	 */
	public boolean isBlockedCommand(String command)
	{
		for(String blocked : API.config.getSettingArrayListString("blocked_battle_commands"))
			if(command.equalsIgnoreCase(blocked)) return true;
		return false;
	}

	/**
	 * Checks all battles and sets them to inactive where need-be.
	 */
	public synchronized void checkForInactiveBattles()
	{
		for(Battle battle : getAllActive())
		{
			int battleID = battle.getID();
			if(!API.data.hasTimedData(battleID, "battle_active"))
			{
				BattleEndEvent battleEvent = new BattleEndEvent(battleID, System.currentTimeMillis());
				API.misc.callEvent(battleEvent);
				if(!battleEvent.isCancelled())
				{
					battle.setActive(false);
				}
			}
		}
	}

	/**
	 * Processes the given characters into a battle.
	 * 
	 * @param hitChar the character being hit.
	 * @param hittingChar the character doing to hitting.
	 */
	public void battleProcess(PlayerCharacter hitChar, PlayerCharacter hittingChar)
	{
		Battle battle = null;
		Battle otherBattle = null;
		Player hit = hitChar.getOwner().getPlayer();
		Player hitting = hittingChar.getOwner().getPlayer();

		if(isInAnyActiveBattle(hitChar))
		{
			battle = getActiveBattle(hitChar);
			if(isInAnyActiveBattle(hittingChar) && getActiveBattle(hittingChar) != battle) otherBattle = getActiveBattle(hittingChar);
		}
		else if(isInAnyActiveBattle(hittingChar))
		{
			battle = getActiveBattle(hittingChar);
			if(isInAnyActiveBattle(hitChar) && getActiveBattle(hitChar) != battle) otherBattle = getActiveBattle(hitChar);
		}
		else if(isNearAnyActiveBattle(hit.getLocation()))
		{
			battle = getActiveBattle(hit.getLocation());
			if(isNearAnyActiveBattle(hitting.getLocation()) && getActiveBattle(hitting.getLocation()) != battle) otherBattle = getActiveBattle(hitting.getLocation());
		}
		else if(isNearAnyActiveBattle(hitting.getLocation()))
		{
			battle = getActiveBattle(hitting.getLocation());
			if(isNearAnyActiveBattle(hit.getLocation()) && getActiveBattle(hit.getLocation()) != battle) otherBattle = getActiveBattle(hit.getLocation());
		}

		if(battle == null)
		{
			Long startTime = System.currentTimeMillis();
			int battleID = API.object.generateInt(5);
			BattleStartEvent battleEvent = new BattleStartEvent(battleID, hitChar, hittingChar, startTime);
			API.misc.callEvent(battleEvent);
			if(!battleEvent.isCancelled()) battle = new Battle(hittingChar, hitChar, startTime, battleID);
		}
		else
		{
			if(otherBattle == null)
			{
				int battleID = battle.getID();
				BattleParticipateEvent battleEvent = new BattleParticipateEvent(battleID, hitChar, hittingChar);
				API.misc.callEvent(battleEvent);
				if(!battleEvent.isCancelled())
				{
					battle.addCharacter(hitChar);
					battle.addCharacter(hittingChar);
					API.data.saveTimedData(battleID, "battle_active", true, 10);
				}
			}
			else
			{
				// Set other battles to inactive
				battle.setActive(false);
				otherBattle.setActive(false);

				BattleCombineEvent battleEvent = null;
				int battleID = API.object.generateInt(5);
				Battle combinedBattle = null;
				if(battle.getStartTime() < otherBattle.getStartTime())
				{
					battleEvent = new BattleCombineEvent(battleID, battle, otherBattle, System.currentTimeMillis());
					API.misc.callEvent(battleEvent);
					if(!battleEvent.isCancelled())
					{
						combinedBattle = new Battle(API.character.getChar(battle.getWhoStarted()), hitChar, battle.getStartTime(), battleID);
						combinedBattle.addCharacter(hittingChar);
					}
					else return;
				}
				else
				{
					battleEvent = new BattleCombineEvent(battleID, otherBattle, battle, System.currentTimeMillis());
					API.misc.callEvent(battleEvent);
					if(!battleEvent.isCancelled())
					{
						combinedBattle = new Battle(API.character.getChar(otherBattle.getWhoStarted()), hitChar, otherBattle.getStartTime(), battleID);
						combinedBattle.addCharacter(hittingChar);
					}
					else return;
				}

				// Add all involved locations and characters from both other events
				ArrayList<Integer> charIDs = new ArrayList<Integer>();
				ArrayList<SerialLocation> locations = new ArrayList<SerialLocation>();

				// Battle
				for(int charID : battle.getCharIDs())
				{
					if(!charIDs.contains(charID)) charIDs.add(charID);
				}
				for(SerialLocation location : battle.getLocations())
				{
					if(!locations.contains(location)) locations.add(location);
				}

				// Other Battle
				for(int charID : otherBattle.getCharIDs())
				{
					if(!charIDs.contains(charID)) charIDs.add(charID);
				}
				for(SerialLocation location : otherBattle.getLocations())
				{
					if(!locations.contains(location)) locations.add(location);
				}

				// Overwrite data in the new combined battle
				combinedBattle.overwriteCharIDs(charIDs);
				combinedBattle.overwriteLocations(locations);
			}
		}
	}
}
