/*
	Copyright (c) 2013 The Demigods Team
	
	Demigods License v1
	
	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.
	
	Definitions
	
	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.
	
	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.
	
	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.
	
	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.
	
	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
	    of http://www.censoredsoftware.com/.
	
	Agreement
	
	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:
	
	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.
	
	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.
	
	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit 
	       permission from the Demigods Team. Copying fees for the 
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.
	
	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.
	
	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:
	
	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.
	
	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.
	
	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.
	
	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.
	
	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.
	
	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.censoredsoftware.Demigods.API;

import java.util.ArrayList;
import java.util.Map.Entry;

import org.bukkit.Location;

import com.censoredsoftware.Demigods.Demigods;
import com.censoredsoftware.Demigods.Objects.Altar;
import com.censoredsoftware.Demigods.Objects.Shrine;

public class BlockAPI
{
	private static final Demigods API = Demigods.INSTANCE;

	/**
	 * Returns all protected blocks as an ArrayList.
	 * 
	 * @return the ArrayList of locations.
	 */
	public ArrayList<Location> getAllBlocks()
	{
		ArrayList<Location> locations = new ArrayList<Location>();

		for(Altar altar : getAllAltars())
			locations.add(altar.getLocation());
		for(Shrine shrine : getAllShrines())
			locations.add(shrine.getLocation());

		return locations;
	}

	/**
	 * Returns all Altars as an ArrayList.
	 * 
	 * @return the ArrayList of Altars.
	 */
	public ArrayList<Altar> getAllAltars()
	{
		if(!API.data.hasBlockData("altars")) return null;

		ArrayList<Altar> altars = new ArrayList<Altar>();

		for(Entry<Integer, Object> obj : API.data.getAllBlockData().get("altars").entrySet())
		{
			altars.add((Altar) obj.getValue());
		}

		return altars;
	}

	/**
	 * Returns all Shrines as an ArrayList.
	 * 
	 * @return the ArrayList of Shrines.
	 */
	public ArrayList<Shrine> getAllShrines()
	{
		if(!API.data.hasBlockData("shrines")) return null;

		ArrayList<Shrine> shrines = new ArrayList<Shrine>();

		for(Entry<Integer, Object> obj : API.data.getAllBlockData().get("shrines").entrySet())
		{
			shrines.add((Shrine) obj.getValue());
		}

		return shrines;
	}

	/**
	 * Returns true if the block at the passed in <code>location</code> is protected.
	 * 
	 * @param location the location to check.
	 * @return true/false depending on if the block is protected or not.
	 */
	public boolean isProtected(Location location)
	{
		return !(getAllAltars() == null && getAllShrines() == null) && (isAltar(location) || isShrine(location));
	}

	/**
	 * Returns true if the block at the passed in <code>location</code> is an Altar.
	 * 
	 * @param location the location to check.
	 * @return true/false depending on if the block is an Altar or not.
	 */
	public boolean isAltar(Location location)
	{
		if(getAllAltars() == null) return false;

		for(Altar altar : getAllAltars())
		{
			if(altar.locationMatches(location)) return true;
		}
		return false;
	}

	/**
	 * Returns true if the block at the passed in <code>location</code> is a Shrine.
	 * 
	 * @param location the location to check.
	 * @return true/false depending on if the block is an Shrine or not.
	 */
	public boolean isShrine(Location location)
	{
		if(getAllShrines() == null) return false;

		for(Shrine altar : getAllShrines())
		{
			if(altar.getLocation().equals(location)) return true;
		}
		return false;
	}

	/**
	 * Returns the Altar at the <code>location</code>.
	 * 
	 * @param location the location to check.
	 * @return the Altar at <code>location</code>.
	 */
	public Altar getAltar(Location location)
	{
		if(getAllAltars() == null) return null;

		for(Altar altar : getAllAltars())
		{
			if(altar.locationMatches(location)) return altar;
		}
		return null;
	}

	/**
	 * Returns the Shrine at the <code>location</code>.
	 * 
	 * @param location the location to check.
	 * @return the Shrine at <code>location</code>.
	 */
	public Shrine getShrine(Location location)
	{
		if(getAllShrines() == null) return null;

		for(Shrine shrine : getAllShrines())
		{
			if(shrine.getLocation().equals(location)) return shrine;
		}
		return null;
	}

	/**
	 * Checks the <code>reference</code> location to validate if the area is safe
	 * for automated generation.
	 * 
	 * @param reference the location to be checked
	 * @param area how big of an area (in blocks) to validate
	 * @return based on if the location is safe to generate at
	 */
	public boolean canGenerateSolid(Location reference, int area)
	{
		Location location = reference.clone();
		location.subtract(0, 1, 0);
		location.add((area / 3), 0, (area / 2));

		// Check ground
		for(int i = 0; i < area; i++)
		{
			if(!location.getBlock().getType().isSolid()) return false;
			location.subtract(1, 0, 0);
		}

		// Check ground adjacent
		for(int i = 0; i < area; i++)
		{
			if(!location.getBlock().getType().isSolid()) return false;
			location.subtract(0, 0, 1);
		}

		// Check ground adjacent again
		for(int i = 0; i < area; i++)
		{
			if(!location.getBlock().getType().isSolid()) return false;
			location.add(1, 0, 0);
		}

		location.add(0, 1, 0);

		// Check air diagonally
		for(int i = 0; i < area + 1; i++)
		{
			if(!location.getBlock().getType().isTransparent()) return false;
			location.add(0, 1, 1);
			location.subtract(1, 0, 0);
		}

		return true;
	}

	/**
	 * Returns true/false depending on if there is an Altar within <code>blocks</code> of <code>location</code>.
	 * 
	 * @param location the location used as the center to check from.
	 * @param blocks the radius of blocks to check with.
	 * @return
	 */
	public boolean altarNearby(Location location, int blocks)
	{
		if(getAllAltars() == null) return false;

		for(Altar altar : getAllAltars())
		{
			if(altar.getLocation().distance(location) <= blocks) return true;
		}
		return false;
	}
}
