/*
	Copyright (c) 2013 The Demigods Team

	Demigods License v1

	This plugin is provided "as is" and without any warranty.  Any express or
	implied warranties, including, but not limited to, the implied warranties
	of merchantability and fitness for a particular purpose are disclaimed.
	In no event shall the authors be liable to any party for any direct,
	indirect, incidental, special, exemplary, or consequential damages arising
	in any way out of the use or misuse of this plugin.

	Definitions

	 1. This Plugin is defined as all of the files within any archive
	    file or any group of files released in conjunction by the Demigods Team,
	    the Demigods Team, or a derived or modified work based on such files.

	 2. A Modification, or a Mod, is defined as this Plugin or a derivative of
	    it with one or more Modification applied to it, or as any program that
	    depends on this Plugin.

	 3. Distribution is defined as allowing one or more other people to in
	    any way download or receive a copy of this Plugin, a Modified
	    Plugin, or a derivative of this Plugin.

	 4. The Software is defined as an installed copy of this Plugin, a
	    Modified Plugin, or a derivative of this Plugin.

	 5. The Demigods Team is defined as Alex Bennett and Alexander Chauncey
	    of http://www.censoredsoftware.com/.

	Agreement

	 1. Permission is hereby granted to use, copy, modify and/or
	    distribute this Plugin, provided that:

	    a. All copyright notices within source files and as generated by
	       the Software as output are retained, unchanged.

	    b. Any Distribution of this Plugin, whether as a Modified Plugin
	       or not, includes this license and is released under the terms
	       of this Agreement. This clause is not dependant upon any
	       measure of changes made to this Plugin.

	    c. This Plugin, Modified Plugins, and derivative works may not
	       be sold or released under any paid license without explicit
	       permission from the Demigods Team. Copying fees for the
	       transport of this Plugin, support fees for installation or
	       other services, and hosting fees for hosting the Software may,
	       however, be imposed.

	    d. Any Distribution of this Plugin, whether as a Modified
	       Plugin or not, requires express written consent from the
	       Demigods Team.

	 2. You may make Modifications to this Plugin or a derivative of it,
	    and distribute your Modifications in a form that is separate from
	    the Plugin. The following restrictions apply to this type of
	    Modification:

	    a. A Modification must not alter or remove any copyright notices
	       in the Software or Plugin, generated or otherwise.

	    b. When a Modification to the Plugin is released, a
	       non-exclusive royalty-free right is granted to the Demigods Team
	       to distribute the Modification in future versions of the
	       Plugin provided such versions remain available under the
	       terms of this Agreement in addition to any other license(s) of
	       the initial developer.

	    c. Any Distribution of a Modified Plugin or derivative requires
	       express written consent from the Demigods Team.

	 3. Permission is hereby also granted to distribute programs which
	    depend on this Plugin, provided that you do not distribute any
	    Modified Plugin without express written consent.

	 4. The Demigods Team reserves the right to change the terms of this
	    Agreement at any time, although those changes are not retroactive
	    to past releases, unless redefining the Demigods Team. Failure to
	    receive notification of a change does not make those changes invalid.
	    A current copy of this Agreement can be found included with the Plugin.

	 5. This Agreement will terminate automatically if you fail to comply
	    with the limitations described herein. Upon termination, you must
	    destroy all copies of this Plugin, the Software, and any
	    derivatives within 48 hours.
 */

package com.censoredsoftware.Demigods.API;

import java.util.ArrayList;

import com.censoredsoftware.Demigods.Demigods;
import com.censoredsoftware.Demigods.Libraries.Objects.Altar;
import com.censoredsoftware.Demigods.Libraries.Objects.PlayerCharacter;
import com.censoredsoftware.Demigods.Libraries.Objects.SerialLocation;

/**
 * API for all warp-related methods.
 */
public class WarpAPI
{
	private static final Demigods API = Demigods.INSTANCE;

	/**
	 * Returns an ArrayList of all warps for <code>character</code>.
	 * 
	 * @param character the character whose warps to gather
	 * @return an ArrayList of the <code>character</code> warps.
	 */
	public ArrayList<SerialLocation> getWarps(PlayerCharacter character)
	{
		if(character == null || API.data.getCharData(character.getID(), "warps") == null) return null;
		return (ArrayList<SerialLocation>) API.data.getCharData(character.getID(), "warps");
	}

	/**
	 * Checks to see if <code>character</code> has a warp for <code>altar</code>.
	 * 
	 * @param altar the altar to be checked.
	 * @param character the character to be checked.
	 * @return true/false depending on if the <code>character</code> has the warp.
	 */
	public boolean hasWarp(Altar altar, PlayerCharacter character)
	{
		if(getWarps(character) == null) return false;
		for(SerialLocation warp : getWarps(character))
		{
			if(API.zone.zoneAltar(warp.unserialize()) == altar) return true;
		}
		return false;
	}

	/**
	 * Returns true if <code>character</code> has invites in their que.
	 * 
	 * @param character the character to check.
	 * @return true/false depending on the presence of invites.
	 */
	public boolean hasInvites(PlayerCharacter character)
	{
		return getInvites(character) != null && !getInvites(character).isEmpty();
	}

	/**
	 * Gets the invite from <code>inviting</code> to <code>invited</code> and
	 * returns a <code>SerialLocation</code>.
	 * 
	 * @param inviting the character who sent the invite.
	 * @param invited the character who received the invite.
	 * @return the <code>SerialLocation</code> of the invite.
	 */
	public SerialLocation getInvite(PlayerCharacter inviting, PlayerCharacter invited)
	{
		if(hasInvites(invited))
		{
			for(SerialLocation invite : getInvites(invited))
			{
				if(invite.getName().equalsIgnoreCase(inviting.getName())) return invite;
			}
		}
		return null;
	}

	/**
	 * Returns the invite for the <code>character</code> with the name <code>name</code>.
	 * 
	 * @param character the character to check.
	 * @param name the name of the invite to get.
	 * @return the <code>SerialLocation</code> of the invite.
	 */
	public SerialLocation getInvite(PlayerCharacter character, String name)
	{
		if(hasInvites(character))
		{
			for(SerialLocation invite : getInvites(character))
			{
				if(invite.getName().equalsIgnoreCase(name)) return invite;
			}
		}
		return null;
	}

	/**
	 * Returns true if <code>invited</code> has already been given an invite from <code>inviting</code>.
	 * 
	 * @param inviting the character the invite is from.
	 * @param invited the character the invite is to.
	 * @return boolean for if the character has been invited or not.
	 */
	public boolean alreadyInvited(PlayerCharacter inviting, PlayerCharacter invited)
	{
		if(getInvite(inviting, invited) != null) return true;
		return false;
	}

	/**
	 * Returns an ArrayList of all invite locations for <code>character</code>.
	 * 
	 * @param character the character whose invites to grab.
	 * @return an ArrayList of invite locations.
	 */
	public ArrayList<SerialLocation> getInvites(PlayerCharacter character)
	{
		return (ArrayList<SerialLocation>) API.data.getCharData(character.getID(), "temp_invites");
	}

	/**
	 * Sends an invite to <code>to</code> from <code>from</code>.
	 * 
	 * @param from the character whom the invite is from.
	 * @param to the character whom the invite is to.
	 */
	public void addInvite(PlayerCharacter from, PlayerCharacter to)
	{
		ArrayList<SerialLocation> invites;
		if(hasInvites(to)) invites = getInvites(to);
		else invites = new ArrayList<SerialLocation>();
		invites.add(new SerialLocation(from.getOwner().getPlayer().getLocation(), from.getName()));
		API.data.saveCharData(to.getID(), "temp_invites", invites);
	}

	/**
	 * Removes <code>invite</code> from <code>invited</code>.
	 * 
	 * @param invited the character to remove the invite from.
	 * @param invite the invite to remove.
	 */
	public void removeInvite(PlayerCharacter invited, SerialLocation invite)
	{
		ArrayList<SerialLocation> invites;
		if(hasInvites(invited)) invites = getInvites(invited);
		else return;
		invites.remove(invite);
		API.data.saveCharData(invited.getID(), "temp_invites", invites);
	}

	/**
	 * Clears all invited for <code>character</code>.
	 * 
	 * @param character the character whose invites to remove.
	 */
	public void clearInvites(PlayerCharacter character)
	{
		API.data.removeCharData(character.getID(), "temp_invites");
	}
}
